Various improvements python venv is now set up automatically deps are now installed automatically on setup or install-server fixed status reporting for install-server stopping at Converting symbols added ./scripts/tracer to make it easier to run the tracer script with venv

diff --git a/scripts/shared b/scripts/shared
--- a/scripts/shared
+++ b/scripts/shared
@@ -78,14 +78,20 @@ export_server_symbols(){
 	local input_path="$1"
 	local output_path="$2"
 
-	echo "${LY} > Copying server binary"
+	echo "${LY} > Copying server binary$R"
 	cp "$input_path" "$output_path"
 
-	echo "${LY} > Stripping DWARF if present"
+	echo "${LY} > Stripping DWARF if present$R"
 	strip --strip-debug "$output_path"
 
-	echo "${LY} > Converting symbols"
-	python3 export-symbols.py "$output_path" "$output_path"
+	echo "${LY} > Converting symbols$R"
+	(source ./python-venv/bin/activate && python3 export-symbols.py "$output_path" "$output_path")
+	local result=$?
+	if [ $result -ne 0 ]; then
+		echo "${LR} !!! Error exporting symbols, aborting$R"
+		exit 1
+	fi
+	echo "${LG} > Symbols converted successfully$R"
 }
 
 copy_server_files(){
@@ -134,7 +140,12 @@ install_server(){
 
 	copy_server_files "$server_files" "$working_directory"
 
-	export_server_symbols "$working_directory/bedrock_server_symbols.debug" "$working_directory/bedrock_server_symbols_test.debug" || echo "${LR} !!! Error exporting symbols, aborting$R" && exit 1
+	export_server_symbols "$working_directory/bedrock_server_symbols.debug" "$working_directory/bedrock_server_symbols_test.debug"
+	local result=$?
+	if [ $result -ne 0 ]; then
+		echo "${LR} !!! Error exporting symbols, aborting$R"
+		exit 1
+	fi
 }
 
 install_modloader(){
@@ -151,4 +162,29 @@ build_all_mods(){
 	local cmake_flags="$2"
 	export -f build_mod && export LIBS=$LIBS
 	find "$mods_code" -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 -n1 -P4 -I '@' bash -c "build_mod @ \"$cmake_flags\" || exit 255" || exit 1
+}
+
+setup_python_venv(){
+	local working_directory="$1"
+	if [ -d "$working_directory/python-venv" ]; then
+		echo "${LY} ! Deleting existing $working_directory/python-venv and recreating$R"
+		rm -rf "$working_directory/python-venv"
+	fi
+	echo "${LY} > Setting up new Python venv in $working_directory/python-venv using $(which python3)$R"
+	python3 -m venv ./python-venv
+	echo "${LG} > Python venv set up successfully in $working_directory/python-venv$R"
+}
+
+install_python_deps(){
+	local working_directory="$1"
+	if [ ! -d "$working_directory/python-venv" ]; then
+		echo "${LR} !!! Python venv not found in $working_directory/python-venv$R"
+		exit 1
+	fi
+	(source "$working_directory/python-venv/bin/activate" && python3 -m pip install -r "$working_directory/python_requirements.txt")
+	local result=$?
+	if [ $result -ne 0 ]; then
+		echo "${LR} !!! Error installing Python deps in venv$R"
+		exit 1
+	fi
 }
